package cz.lukaspolak.typeracer;

import javax.swing.*;
import java.awt.*;

/**
 * This class is responsible for creating the main menu of the application.
 * It is also responsible for handling the events that occur in the main menu.
 */
public class MainMenu extends JFrame {
    /**
     * The main menu panel.
     */
    private JPanel mainPanel;
    /**
     * The button that starts the game.
     */
    private JButton gameBtn;
    /**
     * The button that shows the statistics.
     */
    private JButton statsBtn;
    /**
     * Top label of the main menu (has to be defined because of the GUI manager).
     */
    private JLabel mainMenuLabel;

    /**
     * A constructor for the MainMenu class.
     */
    public MainMenu() {
        super();
    }

    /**
     * This method creates the main menu, sets up all the event handlers and other window properties.
     * Then the window is shown to the user.
     */
    public void createUIComponents() {
        this.setContentPane(this.mainPanel);
        this.setTitle(Constants.GAME_TITLE);
        this.setSize(Constants.WINDOW_WIDTH, Constants.WINDOW_HEIGHT);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null); // center the window on the screen

        gameBtn.addActionListener(e -> handleGameBtn());
        statsBtn.addActionListener(e -> handleStatsBtn());

        this.setVisible(true);
    }

    /**
     * This method is called when the user clicks the "Show stats!" button.
     * It hides the main menu and creates a new StatsForm window.
     *
     * @see StatsForm
     */
    private void handleStatsBtn() {
        StatsForm statsForm = new StatsForm();
        statsForm.createUIComponents();
        this.dispose();
    }

    /**
     * This method is called when the user clicks the "Play Game!" button.
     * It hides the main menu and creates a new Game window.
     *
     * @see Game
     */
    private void handleGameBtn() {
        Game game = new Game();
        game.createUIComponents();
        this.dispose();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
        mainPanel.setBackground(new Color(-1));
        mainMenuLabel = new JLabel();
        mainMenuLabel.setForeground(new Color(-16777216));
        mainMenuLabel.setText("TypeRacer Menu!");
        mainPanel.add(mainMenuLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(10, 10), null, null, 0, false));
        statsBtn = new JButton();
        statsBtn.setText("Show stats!");
        mainPanel.add(statsBtn, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gameBtn = new JButton();
        gameBtn.setText("Play Game!");
        mainPanel.add(gameBtn, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
